services:
  estatein-nest:
    container_name: estatein-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/estatein-next
    working_dir: /usr/src/estatein-next

    networks:
      - client-network

    #production
    command: bash -c "yarn && yarn run build && yarn run start"
    # for dev
    # command: bash -c "npm install && npm run start:dev"

networks:
  client-network:
    driver: bridge
# estatein-front: localhost: 4000
# estatein-back: localhost: 4001
# estatein-batch: localhost: 4002
